// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source=deps.go -destination=mock_test.go -package=core
//

// Package core is a generated GoMock package.
package core

import (
	context "context"
	reflect "reflect"
	model "rpgMonster/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockGPTClient is a mock of GPTClient interface.
type MockGPTClient struct {
	ctrl     *gomock.Controller
	recorder *MockGPTClientMockRecorder
}

// MockGPTClientMockRecorder is the mock recorder for MockGPTClient.
type MockGPTClientMockRecorder struct {
	mock *MockGPTClient
}

// NewMockGPTClient creates a new mock instance.
func NewMockGPTClient(ctrl *gomock.Controller) *MockGPTClient {
	mock := &MockGPTClient{ctrl: ctrl}
	mock.recorder = &MockGPTClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPTClient) EXPECT() *MockGPTClientMockRecorder {
	return m.recorder
}

// GetCompletion mocks base method.
func (m *MockGPTClient) GetCompletion(systemContent, userContent string) (model.GPTAnswer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompletion", systemContent, userContent)
	ret0, _ := ret[0].(model.GPTAnswer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletion indicates an expected call of GetCompletion.
func (mr *MockGPTClientMockRecorder) GetCompletion(systemContent, userContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletion", reflect.TypeOf((*MockGPTClient)(nil).GetCompletion), systemContent, userContent)
}

// MockDBClient is a mock of DBClient interface.
type MockDBClient struct {
	ctrl     *gomock.Controller
	recorder *MockDBClientMockRecorder
}

// MockDBClientMockRecorder is the mock recorder for MockDBClient.
type MockDBClientMockRecorder struct {
	mock *MockDBClient
}

// NewMockDBClient creates a new mock instance.
func NewMockDBClient(ctrl *gomock.Controller) *MockDBClient {
	mock := &MockDBClient{ctrl: ctrl}
	mock.recorder = &MockDBClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBClient) EXPECT() *MockDBClientMockRecorder {
	return m.recorder
}

// CheckPassword mocks base method.
func (m *MockDBClient) CheckPassword(login, password string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPassword", login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckPassword indicates an expected call of CheckPassword.
func (mr *MockDBClientMockRecorder) CheckPassword(login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPassword", reflect.TypeOf((*MockDBClient)(nil).CheckPassword), login, password)
}

// CheckUserByBizID mocks base method.
func (m *MockDBClient) CheckUserByBizID(bizID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserByBizID", bizID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserByBizID indicates an expected call of CheckUserByBizID.
func (mr *MockDBClientMockRecorder) CheckUserByBizID(bizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserByBizID", reflect.TypeOf((*MockDBClient)(nil).CheckUserByBizID), bizID)
}

// CheckUserByLogin mocks base method.
func (m *MockDBClient) CheckUserByLogin(login string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserByLogin", login)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserByLogin indicates an expected call of CheckUserByLogin.
func (mr *MockDBClientMockRecorder) CheckUserByLogin(login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserByLogin", reflect.TypeOf((*MockDBClient)(nil).CheckUserByLogin), login)
}

// CreateNewUser mocks base method.
func (m *MockDBClient) CreateNewUser(login, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewUser", login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewUser indicates an expected call of CreateNewUser.
func (mr *MockDBClientMockRecorder) CreateNewUser(login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewUser", reflect.TypeOf((*MockDBClient)(nil).CreateNewUser), login, password)
}

// CreateNewUserTG mocks base method.
func (m *MockDBClient) CreateNewUserTG(login, password string, telegramID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewUserTG", login, password, telegramID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewUserTG indicates an expected call of CreateNewUserTG.
func (mr *MockDBClientMockRecorder) CreateNewUserTG(login, password, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewUserTG", reflect.TypeOf((*MockDBClient)(nil).CreateNewUserTG), login, password, telegramID)
}

// CreateTask mocks base method.
func (m *MockDBClient) CreateTask(ctx context.Context, task *model.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockDBClientMockRecorder) CreateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockDBClient)(nil).CreateTask), ctx, task)
}

// GetTask mocks base method.
func (m *MockDBClient) GetTask(ctx context.Context, bizID string) (*model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, bizID)
	ret0, _ := ret[0].(*model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockDBClientMockRecorder) GetTask(ctx, bizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockDBClient)(nil).GetTask), ctx, bizID)
}

// GetTaskByIDAndUserID mocks base method.
func (m *MockDBClient) GetTaskByIDAndUserID(ctx context.Context, taskID int64, userID string) (*model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByIDAndUserID", ctx, taskID, userID)
	ret0, _ := ret[0].(*model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByIDAndUserID indicates an expected call of GetTaskByIDAndUserID.
func (mr *MockDBClientMockRecorder) GetTaskByIDAndUserID(ctx, taskID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByIDAndUserID", reflect.TypeOf((*MockDBClient)(nil).GetTaskByIDAndUserID), ctx, taskID, userID)
}

// GetTaskListByUserID mocks base method.
func (m *MockDBClient) GetTaskListByUserID(userID string) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskListByUserID", userID)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskListByUserID indicates an expected call of GetTaskListByUserID.
func (mr *MockDBClientMockRecorder) GetTaskListByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskListByUserID", reflect.TypeOf((*MockDBClient)(nil).GetTaskListByUserID), userID)
}

// GetUserByTGID mocks base method.
func (m *MockDBClient) GetUserByTGID(telegramID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByTGID", telegramID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByTGID indicates an expected call of GetUserByTGID.
func (mr *MockDBClientMockRecorder) GetUserByTGID(telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByTGID", reflect.TypeOf((*MockDBClient)(nil).GetUserByTGID), telegramID)
}

// GetUserByTempToken mocks base method.
func (m *MockDBClient) GetUserByTempToken(tempToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByTempToken", tempToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByTempToken indicates an expected call of GetUserByTempToken.
func (mr *MockDBClientMockRecorder) GetUserByTempToken(tempToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByTempToken", reflect.TypeOf((*MockDBClient)(nil).GetUserByTempToken), tempToken)
}

// UpdateTask mocks base method.
func (m *MockDBClient) UpdateTask(ctx context.Context, task *model.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockDBClientMockRecorder) UpdateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockDBClient)(nil).UpdateTask), ctx, task)
}

// UpdateUserTGID mocks base method.
func (m *MockDBClient) UpdateUserTGID(userID string, telegramID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserTGID", userID, telegramID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserTGID indicates an expected call of UpdateUserTGID.
func (mr *MockDBClientMockRecorder) UpdateUserTGID(userID, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserTGID", reflect.TypeOf((*MockDBClient)(nil).UpdateUserTGID), userID, telegramID)
}
